//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderNumber { get; set; }
        public int ItemID { get; set; }
        public int OrderedQty { get; set; }
        public System.DateTime OrderedDate { get; set; }
    
        public virtual Item Item { get; set; }
    }
}
